# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_auto_20171117_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='message_seen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='unseen_by',
            field=models.ManyToManyField(blank=True, related_name='message_unseen', to=settings.AUTH_USER_MODEL),
        ),
    ]
